FROM jgogstad/arm32v7-debian:jessie
### RUN rpi-update
RUN apt-get update && apt-get install -y \
    wget

WORKDIR /usr/src/app

RUN wget "https://github.com/industlabs/usbserver.git" \
    && tar xzf usbserver \    
RUN chmod +x ./vhusbdarm
RUN sudo ./vhusbdarm
