FROM jgogstad/arm32v7-debian:jessie
### RUN rpi-update
RUN apt-get update && apt-get install -y 

WORKDIR /usr/src/app

RUN wget -O usbserver \
    "https://github.com/industlabs/usbserver.git" \
    && tar xzf usbserver \
    && rm usbserver.git
    
RUN chmod +x ./vhusbdarm
RUN sudo ./vhusbdarm
